/* The following code was generated by JFlex 1.4.1 on 2/17/09 11:52 AM */

/***** JFlex specification for Clojure *****/

package com.bitbakery.clojet.lexer;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import static com.bitbakery.clojet.lexer.ClojureTokenTypes.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 2/17/09 11:52 AM from the specification file
 * <tt>src/com/bitbakery/clojet/lexer/clojure.flex</tt>
 */
public class _ClojureLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\16\1\35"+
    "\1\7\2\16\1\71\1\66\1\37\1\40\1\5\1\14\1\70\1\14"+
    "\1\15\1\6\1\12\11\11\1\36\1\4\4\16\1\64\1\52\1\16"+
    "\1\73\1\60\1\13\1\53\1\16\1\72\1\55\2\16\1\56\1\51"+
    "\1\54\1\47\1\57\1\45\1\61\1\62\1\50\1\46\5\16\1\43"+
    "\1\17\1\44\1\65\1\16\1\67\1\27\1\32\1\30\1\60\1\21"+
    "\1\53\1\16\1\72\1\24\2\16\1\23\1\51\1\20\1\47\1\26"+
    "\1\45\1\33\1\25\1\31\1\34\1\16\1\22\3\16\1\41\1\10"+
    "\1\42\1\63\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\3\3\2\1\1\4\1\5\1\1\1\6"+
    "\1\2\4\1\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\4\1\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\2\0\1\26\1\0\1\27\1\30\4\5"+
    "\5\31\3\1\1\32\1\1\2\7\2\1\1\33\2\1"+
    "\1\34\1\35\2\0\1\5\4\0\1\36\1\37\5\1"+
    "\1\40\1\41\1\5\3\0\1\42\1\43\1\1\1\44"+
    "\1\1\1\45\2\1\3\0\1\46\1\47\4\1\2\0"+
    "\12\1\1\50\1\51\1\52\1\53";

  private static int [] zzUnpackAction() {
    int [] result = new int[117];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\74\0\170\0\74\0\264\0\360\0\u012c\0\u0168"+
    "\0\u01a4\0\u01e0\0\u021c\0\u0258\0\u0294\0\u02d0\0\u030c\0\u0348"+
    "\0\u0384\0\u03c0\0\74\0\74\0\74\0\74\0\74\0\74"+
    "\0\u03fc\0\u0438\0\u0474\0\u04b0\0\u04ec\0\u012c\0\74\0\74"+
    "\0\74\0\74\0\74\0\264\0\u0528\0\u0564\0\u05a0\0\74"+
    "\0\74\0\u05dc\0\u0618\0\u0654\0\u012c\0\74\0\u0690\0\u06cc"+
    "\0\u0708\0\u0744\0\u0780\0\u07bc\0\u07f8\0\u012c\0\u0834\0\u0870"+
    "\0\74\0\u08ac\0\u08e8\0\u012c\0\u0924\0\u0960\0\u012c\0\74"+
    "\0\u099c\0\u09d8\0\u0a14\0\u0a50\0\u0a8c\0\u0ac8\0\u0b04\0\u012c"+
    "\0\u012c\0\u0b40\0\u0b7c\0\u0bb8\0\u0bf4\0\u0c30\0\u0c6c\0\u05a0"+
    "\0\u0ca8\0\u0ce4\0\u0d20\0\u0d5c\0\u012c\0\u012c\0\u0d98\0\u012c"+
    "\0\u0dd4\0\u012c\0\u0e10\0\u0e4c\0\u0e88\0\u0ec4\0\u0f00\0\u012c"+
    "\0\u012c\0\u0f3c\0\u0f78\0\u0fb4\0\u0ff0\0\u102c\0\u1068\0\u10a4"+
    "\0\u10e0\0\u111c\0\u1158\0\u1194\0\u11d0\0\u120c\0\u1248\0\u1284"+
    "\0\u12c0\0\u012c\0\u012c\0\u012c\0\u012c";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[117];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\2\7\1\10\1\7"+
    "\2\11\1\7\1\12\1\13\1\7\1\14\1\15\2\7"+
    "\1\16\1\17\4\7\1\20\3\7\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\2\7\1\20"+
    "\1\32\1\7\1\33\1\15\1\17\1\16\1\7\1\34"+
    "\2\7\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\2\7\76\0\1\4\74\0\1\44\1\45\67\0\1\45"+
    "\2\46\1\45\3\6\1\45\5\6\1\45\1\6\1\45"+
    "\15\6\10\45\16\6\1\45\1\6\5\45\2\6\4\0"+
    "\3\7\1\0\5\7\1\0\1\7\1\0\15\7\10\0"+
    "\16\7\1\0\1\7\5\0\2\7\10\0\1\47\54\0"+
    "\1\50\1\51\11\0\3\7\1\0\1\7\2\11\1\52"+
    "\1\7\1\53\1\7\1\0\1\7\1\52\13\7\10\0"+
    "\16\7\1\0\1\7\5\0\2\7\4\0\3\7\1\0"+
    "\1\7\1\54\1\55\2\7\1\0\1\7\1\0\15\7"+
    "\10\0\16\7\1\0\1\7\5\0\2\7\11\0\2\53"+
    "\65\0\3\56\1\0\5\56\1\0\1\56\1\0\1\57"+
    "\4\56\1\60\3\56\1\61\1\56\1\62\2\56\7\0"+
    "\16\56\1\0\1\56\5\0\2\56\4\0\3\7\1\0"+
    "\5\7\1\0\1\7\1\0\4\7\1\63\10\7\10\0"+
    "\10\7\1\63\5\7\1\0\1\7\5\0\2\7\4\0"+
    "\3\7\1\0\3\7\1\64\1\7\1\0\1\7\1\0"+
    "\1\7\1\64\13\7\10\0\2\7\1\65\13\7\1\0"+
    "\1\7\5\0\2\7\4\0\3\7\1\0\5\7\1\0"+
    "\1\7\1\0\15\7\10\0\6\7\1\66\7\7\1\0"+
    "\1\7\5\0\2\7\4\0\3\7\1\0\5\7\1\0"+
    "\1\7\1\0\13\7\1\67\1\7\10\0\14\7\1\67"+
    "\1\7\1\0\1\7\5\0\2\7\17\21\1\70\15\21"+
    "\1\71\36\21\4\0\3\22\1\0\5\22\1\0\1\22"+
    "\1\0\15\22\10\0\16\22\1\0\1\22\5\0\2\22"+
    "\4\0\3\7\1\0\5\7\1\0\1\7\1\0\14\7"+
    "\1\72\10\0\1\7\1\72\14\7\1\0\1\7\5\0"+
    "\2\7\4\0\3\7\1\0\5\7\1\0\1\7\1\0"+
    "\1\7\1\73\13\7\10\0\16\7\1\0\1\7\5\0"+
    "\2\7\4\0\3\7\1\0\5\7\1\0\1\7\1\0"+
    "\1\74\6\7\1\75\5\7\10\0\5\7\1\75\1\7"+
    "\1\74\6\7\1\0\1\7\5\0\2\7\4\0\3\7"+
    "\1\0\3\7\1\76\1\7\1\0\1\7\1\0\1\7"+
    "\1\76\13\7\10\0\2\7\1\77\13\7\1\0\1\7"+
    "\5\0\2\7\64\0\1\100\7\0\1\45\2\46\71\45"+
    "\1\0\2\46\71\0\5\47\1\101\2\47\1\102\63\47"+
    "\4\0\3\7\1\0\1\7\2\54\1\7\1\54\1\0"+
    "\1\7\1\0\15\7\10\0\16\7\1\0\1\7\5\0"+
    "\2\7\11\0\2\53\1\103\5\0\1\103\56\0\3\7"+
    "\1\0\1\7\2\54\2\7\1\0\1\7\1\0\15\7"+
    "\10\0\16\7\1\0\1\7\5\0\2\7\21\0\1\104"+
    "\100\0\1\105\74\0\1\106\65\0\1\107\56\0\3\7"+
    "\1\0\5\7\1\0\1\7\1\0\3\7\1\110\11\7"+
    "\10\0\11\7\1\110\4\7\1\0\1\7\5\0\2\7"+
    "\4\0\3\7\1\0\5\7\1\0\1\7\1\0\11\7"+
    "\1\111\3\7\10\0\3\7\1\111\12\7\1\0\1\7"+
    "\5\0\2\7\4\0\3\7\1\0\5\7\1\0\1\7"+
    "\1\0\15\7\10\0\2\7\1\112\13\7\1\0\1\7"+
    "\5\0\2\7\4\0\3\7\1\0\5\7\1\0\1\7"+
    "\1\0\14\7\1\113\10\0\1\7\1\113\14\7\1\0"+
    "\1\7\5\0\2\7\1\21\2\0\71\21\4\0\3\7"+
    "\1\0\5\7\1\0\1\7\1\0\15\7\10\0\2\7"+
    "\1\114\13\7\1\0\1\7\5\0\2\7\4\0\3\7"+
    "\1\0\5\7\1\0\1\7\1\0\11\7\1\115\3\7"+
    "\10\0\3\7\1\115\12\7\1\0\1\7\5\0\2\7"+
    "\4\0\3\7\1\0\5\7\1\0\1\7\1\0\3\7"+
    "\1\116\11\7\10\0\11\7\1\116\4\7\1\0\1\7"+
    "\5\0\2\7\4\0\3\7\1\0\5\7\1\0\1\7"+
    "\1\0\15\7\10\0\6\7\1\117\7\7\1\0\1\7"+
    "\5\0\2\7\5\47\1\101\1\0\72\47\1\101\1\47"+
    "\1\120\1\102\63\47\11\0\2\121\1\0\1\121\101\0"+
    "\1\122\100\0\1\123\76\0\1\56\72\0\1\124\46\0"+
    "\3\7\1\0\5\7\1\0\1\7\1\0\6\7\1\125"+
    "\6\7\10\0\12\7\1\125\3\7\1\0\1\7\5\0"+
    "\2\7\4\0\3\7\1\0\3\7\1\126\1\7\1\0"+
    "\1\7\1\0\1\7\1\126\13\7\10\0\16\7\1\0"+
    "\1\7\5\0\2\7\4\0\3\7\1\0\5\7\1\0"+
    "\1\7\1\0\11\7\1\127\3\7\10\0\3\7\1\127"+
    "\12\7\1\0\1\7\5\0\2\7\4\0\3\7\1\0"+
    "\5\7\1\0\1\7\1\0\7\7\1\130\5\7\10\0"+
    "\5\7\1\130\10\7\1\0\1\7\5\0\2\7\4\0"+
    "\3\7\1\0\5\7\1\0\1\7\1\0\5\7\1\131"+
    "\7\7\10\0\15\7\1\131\1\0\1\7\5\0\2\7"+
    "\4\0\3\7\1\0\5\7\1\0\1\7\1\0\1\132"+
    "\4\7\1\133\7\7\10\0\4\7\1\134\2\7\1\132"+
    "\5\7\1\133\1\0\1\7\5\0\2\7\11\0\2\121"+
    "\104\0\1\135\100\0\1\136\77\0\1\137\43\0\3\7"+
    "\1\0\3\7\1\140\1\7\1\0\1\7\1\0\1\7"+
    "\1\140\13\7\10\0\16\7\1\0\1\7\5\0\2\7"+
    "\4\0\3\7\1\0\3\7\1\141\1\7\1\0\1\7"+
    "\1\0\1\7\1\141\13\7\10\0\16\7\1\0\1\7"+
    "\5\0\2\7\4\0\3\7\1\0\5\7\1\0\1\7"+
    "\1\0\11\7\1\142\3\7\10\0\3\7\1\142\12\7"+
    "\1\0\1\7\5\0\2\7\4\0\3\7\1\0\3\7"+
    "\1\143\1\7\1\0\1\7\1\0\1\7\1\143\5\7"+
    "\1\144\4\7\1\145\10\0\1\7\1\145\3\7\1\144"+
    "\10\7\1\0\1\7\5\0\2\7\24\0\1\146\70\0"+
    "\1\56\105\0\1\147\44\0\3\7\1\0\5\7\1\0"+
    "\1\7\1\0\13\7\1\150\1\7\10\0\14\7\1\150"+
    "\1\7\1\0\1\7\5\0\2\7\4\0\3\7\1\0"+
    "\5\7\1\0\1\7\1\0\11\7\1\151\3\7\10\0"+
    "\3\7\1\151\12\7\1\0\1\7\5\0\2\7\4\0"+
    "\3\7\1\0\5\7\1\0\1\7\1\0\10\7\1\152"+
    "\4\7\10\0\16\7\1\0\1\7\5\0\1\7\1\152"+
    "\4\0\3\7\1\0\5\7\1\0\1\7\1\0\3\7"+
    "\1\153\11\7\10\0\11\7\1\153\4\7\1\0\1\7"+
    "\5\0\2\7\20\0\1\136\73\0\1\56\57\0\3\7"+
    "\1\0\5\7\1\0\1\7\1\0\14\7\1\154\10\0"+
    "\1\7\1\154\14\7\1\0\1\7\5\0\2\7\4\0"+
    "\3\7\1\0\5\7\1\0\1\7\1\0\15\7\10\0"+
    "\16\7\1\0\1\7\5\0\1\155\1\7\4\0\3\7"+
    "\1\0\5\7\1\0\1\7\1\0\13\7\1\156\1\7"+
    "\10\0\14\7\1\156\1\7\1\0\1\7\5\0\2\7"+
    "\4\0\3\7\1\0\5\7\1\0\1\7\1\0\11\7"+
    "\1\157\3\7\10\0\3\7\1\157\12\7\1\0\1\7"+
    "\5\0\2\7\4\0\3\7\1\0\5\7\1\0\1\7"+
    "\1\0\10\7\1\160\4\7\10\0\16\7\1\0\1\7"+
    "\5\0\1\7\1\160\4\0\3\7\1\0\5\7\1\0"+
    "\1\7\1\0\15\7\10\0\2\7\1\161\13\7\1\0"+
    "\1\7\5\0\2\7\4\0\3\7\1\0\5\7\1\0"+
    "\1\7\1\0\15\7\10\0\2\7\1\162\13\7\1\0"+
    "\1\7\5\0\2\7\4\0\3\7\1\0\5\7\1\0"+
    "\1\7\1\0\4\7\1\163\10\7\10\0\10\7\1\163"+
    "\5\7\1\0\1\7\5\0\2\7\4\0\3\7\1\0"+
    "\5\7\1\0\1\7\1\0\11\7\1\164\3\7\10\0"+
    "\3\7\1\164\12\7\1\0\1\7\5\0\2\7\4\0"+
    "\3\7\1\0\5\7\1\0\1\7\1\0\15\7\10\0"+
    "\13\7\1\165\2\7\1\0\1\7\5\0\2\7";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4860];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\1\1\1\11\16\1\6\11\6\1\5\11"+
    "\2\0\1\1\1\0\2\11\4\1\1\11\12\1\1\11"+
    "\6\1\1\11\2\0\1\1\4\0\12\1\3\0\10\1"+
    "\3\0\6\1\2\0\16\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[117];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
    StringBuffer string = new StringBuffer();


  public _ClojureLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public _ClojureLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 166) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  // For Demetra compatibility
  public void reset(CharSequence buffer, int initialState){
    zzBuffer = buffer;
    zzBufferArray = null; 
    zzCurrentPos = zzMarkedPos = zzStartRead = 0;
    zzPushbackPos = 0;
    zzAtEOF = false;
    zzAtBOL = true;
    zzEndRead = buffer.length();
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = zzLexicalState;


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL.charAt(zzCurrentPosL++);
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL.charAt(zzCurrentPosL++);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 26: 
          { return IF;
          }
        case 44: break;
        case 12: 
          { return RIGHT_CURLY;
          }
        case 45: break;
        case 41: 
          { return DEFMULTI;
          }
        case 46: break;
        case 32: 
          { return DEF;
          }
        case 47: break;
        case 40: 
          { return DEFMACRO;
          }
        case 48: break;
        case 1: 
          { return SYMBOL;
          }
        case 49: break;
        case 8: 
          { return KEYWORD;
          }
        case 50: break;
        case 19: 
          { return BACKQUOTE;
          }
        case 51: break;
        case 39: 
          { return FALSE;
          }
        case 52: break;
        case 9: 
          { return LEFT_PAREN;
          }
        case 53: break;
        case 20: 
          { return COMMA;
          }
        case 54: break;
        case 6: 
          { return DOT;
          }
        case 55: break;
        case 21: 
          { return REST;
          }
        case 56: break;
        case 7: 
          { return STRING_LITERAL;
          }
        case 57: break;
        case 33: 
          { return BLOCK_COMMENT;
          }
        case 58: break;
        case 23: 
          { return METADATA;
          }
        case 59: break;
        case 42: 
          { return DEFSTRUCT;
          }
        case 60: break;
        case 14: 
          { return RIGHT_SQUARE;
          }
        case 61: break;
        case 3: 
          { return WHITESPACE;
          }
        case 62: break;
        case 22: 
          { return LINE_COMMENT;
          }
        case 63: break;
        case 18: 
          { return QUOTE;
          }
        case 64: break;
        case 5: 
          { return NUMERIC_LITERAL;
          }
        case 65: break;
        case 28: 
          { return DO;
          }
        case 66: break;
        case 10: 
          { return RIGHT_PAREN;
          }
        case 67: break;
        case 24: 
          { return VAR_QUOTE;
          }
        case 68: break;
        case 37: 
          { return DEFN;
          }
        case 69: break;
        case 11: 
          { return LEFT_CURLY;
          }
        case 70: break;
        case 27: 
          { return FN;
          }
        case 71: break;
        case 25: 
          { return CHAR_LITERAL;
          }
        case 72: break;
        case 43: 
          { return DEFMETHOD;
          }
        case 73: break;
        case 30: 
          { return NIL;
          }
        case 74: break;
        case 4: 
          { return REGEX;
          }
        case 75: break;
        case 31: 
          { return LET;
          }
        case 76: break;
        case 38: 
          { return QUOTE_KEYWORD;
          }
        case 77: break;
        case 35: 
          { return TRUE;
          }
        case 78: break;
        case 17: 
          { return META;
          }
        case 79: break;
        case 2: 
          { return BAD_CHARACTER;
          }
        case 80: break;
        case 36: 
          { return META_KEYWORD;
          }
        case 81: break;
        case 34: 
          { return LOOP;
          }
        case 82: break;
        case 13: 
          { return LEFT_SQUARE;
          }
        case 83: break;
        case 15: 
          { return UNQUOTE;
          }
        case 84: break;
        case 16: 
          { return DEREF;
          }
        case 85: break;
        case 29: 
          { return UNQUOTE_SPLICE;
          }
        case 86: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
